# Generated by Django 5.1.7 on 2025-03-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="project",
            new_name="projects",
        ),
    ]
